### PR TITLE
Update Python I notebook to include and use the with command

### PR DESCRIPTION
**Pull request by fwimp**
fixes issue #21

### CODE REVIEW

**Comment by davidorme** [comment]
I think it is worth mentioning that `with` isn't  just for file IO. It is a context manager that has an common use case for file management. I don't know whether you want to spell that out in more detail (like [here](https://dbader.org/blog/python-context-managers-and-with-statement)), but it is worth knowing the more general structure of with.

**Comment by fwimp** [comment]
Thing is 95% of when you use with is for files, and understanding its broader use requires also knowing a lot more about file locks, python, and classes specifically. I completely agree that understanding context managers is a great thing, but I cannot see a way to introduce that so early when this is basically the first real coding they may ever have done. Maybe go back to it in an appendix or in Python II and explain a bit more about it?

**Comment by davidorme** [comment]
Agreed - but I'm thinking of just a little extra text so they don't think it is only file handling: 

The `with` statement is not just for opening files. It is a *context manager*, which is basically a set of common instructions needed to handle a particular job. For file IO, that means using `with` automatically checks the file exists and then closes it properly at the end of the block, but there are other kinds of operations that can use a `with` statement to make your code safer and shorter.

**Comment by fwimp** [comment]
Yeah that's fair. Do you have an easy example of another use?

I'll add some extra stuff and submit it as a separate PR when this one is approved by @mhasoba

**Comment by davidorme** [comment]
If they’ve been introduced to numpy:

https://numpy.org/doc/stable/reference/generated/numpy.printoptions.html


On 19 Nov 2020, at 10:50, Francis Windram <notifications@github.com<mailto:notifications@github.com>> wrote:

This email from notifications@github.com<mailto:notifications@github.com> originates from outside Imperial. Do not click on links and attachments unless you recognise the sender. If you trust the sender, add them to your safe senders list<https://spam.ic.ac.uk/SpamConsole/Senders.aspx> to disable email stamping for this address.



Yeah that's fair. Do you have an easy example of another use?

I'll add some extra stuff and submit it as a separate PR when this one is approved by @mhasoba<https://github.com/mhasoba>

**Comment by mhasoba** [comment]
Looks good - great addition.

**Pull request merged**
