### PR TITLE
Layout ifx

### PR DESCRIPTION
**Pull request by smith558**

### CODE REVIEW

**Review by mhasoba — APPROVED** [review]
Approved and merging now. see my general comment, @smith558

**Comment by smith558** [comment]
> Thanks, @smith558 !
> 
> I am merging your changes.
> 
> Can you please add some notes on the fix (is this an issue that needs to be raised with the jupyter book devs?)

So this is not an issue with `jupyter-book` package I believe. I noticed that since the last and during the recent builds multiple major versions of `jupyter-book` were released, some with breaking changes (e.g. https://jupyterbook.org/en/stable/reference/_changelog.html#new-and-breaking and https://jupyterbook.org/en/stable/explain/migration.html). Looking at the git history, it doesn't seem the code was necessarily updated to comply with these, and because the version of `jupyter-book` used in the repo was not locked, the versions drifted since the last versions that were compatible with the way the code is written, this goes for `Sphinx` too.

I have 2 recommendations:
1. Update the repository code up to a certain `jupyter-book` version and lock that version using a package manager, each time a new major version release is done since then, upgrade cautiously with consideration for breaking changes.
2. Move away from using solely `pip` for package management and add https://python-poetry.org/ which is currently considered as the next generation Python package manager (@fwimp thoughts?) and generally resolves dependencies better. [optional]
3. Remove the `ghp-import -n -p -f content/_build/html` deployment method and either make everyone just merge to `master` and take care of deployment (nominated person) or a proper GitHub action needs to be configured. The `ghp-import` is breaking your version control since people can deploy from whichever branch but do not necessarily need to synchronise with `master`, and they can go on with this for months until a merge is requested and conflicts appear. This is especially important since you are using `-f` flag which allows force pushing. This will become a much larger issue once you have more contributors. For example, I noticed deployments recently seemed to be done both from `master` and `mathsforbiologists` branches, yet these were not necessarily synchronised at those times (at least according to the git history). This method also breaks git history as it doesn't tell you which version was last deployed, since anyone can deploy from any branch.

@fwimp please feedback on anything, maybe I wrote some bs or misunderstood something.

**Comment by smith558** [comment]
Going forward, I could take care of tasks 2) and 3) at some point.

**Comment by davidorme** [comment]
> 2\. Move away from using solely `pip` for package management and add https://python-poetry.org/ which is currently considered as the next generation Python package manager (@fwimp thoughts?) and generally resolves dependencies better. [optional]

There's a cost to doing this in that everyone contributing to the repo then needs to be comfortable with virtual environments and remembering to do all their work on the repo in that environment. _But_ that's a tiny cost compared to the advantages of having a stable defined build environment where we have fine-grained control over the package versions and can make planned upgrades. I use `poetry` a  lot in other projects and it is what the Imperial research software engineer team recommend.

If you're feeling cutting edge, I note that the guys who wrote `ruff` (awesome tool for code-linting and formatting) seem to have decided that `poetry` is now too old school and are developing a fast Python package manager using `rust` ( https://github.com/astral-sh/uv) but that is still officially in development (version `0.4.6`), where `poetry` is stable.

**Comment by davidorme** [comment]
And honestly, if you're going down that line it might be worth looking at a pre-commit tool chain with auto-linting etc to enforce common standards across the repo, although the inputs are sufficiently diverse (markdown, ipynb, latex) that this might just be a massive pain in the arse.

**Comment by smith558** [comment]
@davidorme the whole https://astral.sh/ tools set seems very cool, saving that, though bringing it here might be a bit unnecessary indeed

**Comment by davidorme** [comment]
The `ruff` tool is _fantastic_. It basically replaces `black`, `isort`, `flake8/pyflakes`, provides a bunch of other functionality and is extremely fast. @mhasoba - if the CMEE guys aren't using it in their python projects, then they should.

**Comment by mhasoba** [comment]
> Going forward, I could take care of tasks 2) and 3) at some point.

@smith558 , have a look at the proposal in issue #132

**Pull request merged**
